import streamlit as st

tab1, tab2 = st.tabs(["Project Analysis Questions", "Data Description"])
with tab1:
    st.subheader("Project Objective")
    st.write('Q : What did you set out to study?')
    st.write('    * Inspired by an article about a Korean cafe (Ediya Coffe) strategically placing its stores near Starbucks, I wanted to investigate how Starbucks uses data for location decisions. My project aimed to explore whether Starbucks considers demographic and health factors when selecting store locations in Los Angeles. To achieve this, I analyzed the correlation the number of Starbucks stores per ZIP code and demographic or health data.')

    st.subheader("Discoveries and Conclusions")
    st.write('Q : What were your findings?  Were your original assumptions confirmed?')
    st.write('    * My research found unexpectedly weak correlations between the number of Starbucks locations and demographic or health variables in Los Angeles ZIP codes. The correlation coefficients ranged from -0.26 to +0.23. This contradicted my hypothesis, suggesting Starbucks might not strategically consider the demographic or health factors when choosing store locations. Or the obtained variables might be the main factor for their decision.')
    
    st.subheader("Difficulties")
    st.write('Q : What difficulties did you have in completing the project?')
    st.write('1. Ensuring Data Quality and Completeness')
    st.write('    * Some ZIP codes had missing or incomplete data. Considerable time was spent cleaning any empty or inconsistent data.')
    st.write('2. Challenges with Data Granularity : Finding Data with ZIP Codes')
    st.write('    * Most of the publicly available data was provided in formats like state, county, or geographic coordinates, rather than ZIP codes. This made it difficult to align datasets effectively.')

    st.subheader("Additional Skills Required")
    st.write("Q : What skills did you wish you had while you were doing the project?")
    st.write('1. Advanced Geospatial Data Handling Skills')
    st.write('    * With more advanced capabilities in geospatial data handling, I could have enhanced the Starbucks Location map by adding additional interactive layers. For example, I would have added layers for variables such as total population or median household income, which users could select and visualize on the map. This functionality would have provided users deeper insights into the demographic or health data contexts in regards to Starbucks locations.')
    st.write('2. Machine Learning and Predictive Modeling')
    st.write('    * With a stronger foundation in machine learning, I could have incorporated a predictive model into the project. This model would allow users to input demographic and health data for a specific ZIP code and predict the potential number of Starbucks locations in that area.')

    st.subheader("Areas of Future Developments")
    st.write("Q : What would you do “next” to expand or augment the project?    ")
    st.write('1. Expand Geographic Scope')
    st.write('    * Widening the analysis beyond Los Angeles to include the entire United States or even a global perspective would enable a comparative analysis across different regions and markets, providing deeper insights into Starbucks location strategies in diverse settings.')
    st.write('2.  Additional Interactive Layers on Map')
    st.write('    * Add more interactive layers to the Starbucks Location map, including total population, median household income, and other relevant metrics, allowing user interaction.')
    st.write('3. Including Other Factors')
    st.write('    * Expanding the project to include other variables like real estate prices could reveal how property costs influence Starbucks store placement. Assessing traffic patterns and public transport accessibility could also provide insights into customer inflow.')

with tab2:
    st.subheader("Dataset 1: Starbucks Location Data")
    st.markdown('[Starbucks Store Locator](https://www.starbucks.com/store-locator)')
    st.markdown('[Subdata : LA Zipcodes](https://catalog.data.gov/dataset/zip-codes-within-the-city-of-los-angeles/resource/c03a9708-ed4c-4321-93cf-6721b0104369)')
    st.write('The dataset [starbucks_LA_counts_per_zipcode.csv] was generated by scraping the official Starbucks store locator website, utilizing Los Angeles ZIP codes from a publicly available source. It presents aggregated information on Starbucks locations per ZIP code, without duplicates.')


    st.subheader('Dataset 2: Demographics Data by ZIP Code')
    st.markdown('[United States Census Bureau API](https://api.census.gov/data/2022/acs/acs5/variables.html)')
    st.write('This dataset is from the United States Census Bureau API American Community Survey 5-Year Data for 2022. It offers demographic data including total population, median household income, and employment rates, and more. It filters out ZIP codes not listed in [LA_City_ZIP_code.csv].')

    st.subheader('Dataset 3: Filtered LA Health Data')
    st.markdown('[CDC Health Data](https://chronicdata.cdc.gov/500-Cities-Places/PLACES-ZCTA-Data-GIS-Friendly-Format-2023-release/kee5-23sr/about_data)')
    st.write('Health-related data were obtained from the Centers for Disease Control and Prevention PLACES ZCTA Data in 2023. It offers health and epidemiological statistics for the entire U.S. Only selected features such as obesity rates or access to health insurance were selected, assuming those features might correlate highly with Starbucks location strategy. It again filters out ZIP codes not listed in [LA_City_ZIP_code.csv].')

    st.subheader('Merged Data')
    st.write('These 3 datasets were merged using ZIP codes as a key identifier, into [uncleaned_full_merged_data.csv] file. After data cleaning, the final cleaned dataset [starbucks_health_location_demographic_merged.csv] was generated.')

    st.subheader('Additional Data : Longitude and Latitude Data for ZIP Codes')
    st.markdown('[Subdata : US Zip Code with Longitude and Latitude](https://redivis.com/datasets/d5sz-fq0mbm2ty)')
    st.write('Additional ZIP code data including longitude and latitude were acquired from Stanford University Redivis.com. This geospatial data was used to create the interactive map.')